app/models.py
class Contactor():
    def __init__(self, username, email, phonenumber, message):
        self.username = username
        self.email = email
        self.phonenumber = phonenumber
        self.message = message

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp

class ContactMsg(FlaskForm):
    #name, email, phoneNumber, message
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Length(1, 64), Email()])
    phonenumber = StringField('Phone', validators=[DataRequired(), Length(8, 20),
        Regexp('^[1-9][0-9]*$', 0, 'Phone number format error')])
    message = StringField("Message", validators=[DataRequired()])
    submit = SubmitField('SEND')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from config import config
from flask_mail import Mail

bootstrap = Bootstrap()
mail = Mail()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    #moment, db

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app
    

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
import logging
from flask import render_template, url_for, redirect, current_app
from .forms import ContactMsg
from . import main
from ..email import send_email
from ..models import Contactor

def send_contact_email(app, form):
    username = form.username.data
    email = form.email.data
    phonenumber = form.phonenumber.data
    message = form.message.data

    contactor = Contactor(username, email, phonenumber, message)
    send_email(app.config['CONTACT_RECEIVER'], 'Contactor', 'mail/contactor', contactor=contactor)

@main.route('/', methods=['GET', 'POST'])
def index():
    app = current_app._get_current_object()
    form = ContactMsg()
    if form.validate_on_submit():
        #send email to joyousContect@outlook.com
        if form.validate_on_submit():
            send_contact_email(app, form)
    return render_template('index.html', form=form)

@main.route('/home')
def home():
    return redirect(url_for('.index'))

@main.route('/services')
def services():
    return render_template('services.html')

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/pricing')
def pricing():
    return render_template('pricing.html')

@main.route('/contact', methods=['GET', 'POST'])
def contact():
    app = current_app._get_current_object()
    form = ContactMsg()
    if form.validate_on_submit():
        send_contact_email(app, form)
        return redirect(url_for('.index'))
    return render_template('contact.html', form=form)

app/templates/about.html
{% extends "base.html" %}

{% block content %}
<!-- about section start -->
{% include 'sections/about_section.html' %}
<!-- about section end -->
<!-- join us section start -->
{% include 'sections/joinus_section.html' %}
<!-- join us section end -->
{% endblock content %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}
YingRuiTest(盈悦测试页面)
{% endblock title %}

{%block metas%}
<!-- basic -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- mobile metas -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<!-- site metas -->
<title>Buzzed</title>
<meta name="keywords" content="">
<meta name="description" content="">
<meta name="author" content="">
{%endblock metas%}

{% block styles %}
<!-- bootstrap css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<!-- style css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<!-- Responsive-->
<link rel="stylesheet" href="{{ url_for('static', filename='css/responsive.css') }}">
<!-- fevicon -->
<link rel="icon" href="{{ url_for('static', filename='images/fevicon.png') }}" type="image/gif" />
<!-- Scrollbar Custom CSS -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.mCustomScrollbar.min.css') }}">
<!-- Tweaks for older IEs-->
<link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<!-- owl stylesheets --> 
<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
{% endblock styles %}

{% block body -%}
    
    {% block navbar %}
    <!-- header top section start -->
    <div class="header_top">
        <div class="container">
        <div class="row">
            <div class="col-sm-5">
            <div class="contact_main">
                <div class="contact_left">
                <div class="call_text"><a href="#"><img src="{{ url_for('static', filename='images/call-icon.png') }}"><span class="call_text_left">+01 1234567890</span></a></div>
                </div>
                <div class="contact_right">
                <div class="call_text">Make an appointment</div>
                </div>
            </div>
            </div>
            <div class="col-sm-2">
            <div class="logo"><a href="index.html"><img src="{{ url_for('static', filename='images/logo.png') }}"></a></div>
            </div>
            <div class="col-sm-5">
            <div class="contact_main">
                <div class="contact_left">
                <div class="call_text"><a href="#"><img src="{{ url_for('static', filename='images/mail-icon.png') }}"><span class="call_text_left">Demo@gmail.com</span></a></div>
                </div>
                <div class="contact_right">
                <div class="call_text"><a href="#"><img src="{{ url_for('static', filename='images/map-icon.png') }}"><span class="call_text_left">+01 9876543210</span></a></div>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <!-- header top section end -->
    <!-- header section start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('main.home') }}">HOME</a>
            <a class="nav-item nav-link" href="{{ url_for('main.services') }}">SERVICES</a>
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">ABOUT</a>
            <a class="nav-item nav-link" href="{{ url_for('main.pricing') }}">PRICING</a>
            <a class="nav-item nav-link" href="{{ url_for('main.contact') }}">CONTACT US</a>
        </div>
        </div>
    </nav>
    <!-- header section end -->
    {% endblock navbar %}

    {% block content -%}
    {%- endblock content %}

    <!-- footer section start -->
    <div class="footer_section layout_padding">
        <div class="container">
          <div class="social_icon">
            <ul>
              <li><a href="#"><img src="{{ url_for('static', filename='images/fb-icon.png') }}"></a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/twitter-icon.png') }}"></a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/linkdin-icon.png') }}"></a></li>
              <li><a href="#"><img src="{{ url_for('static', filename='images/instagram-icon.png') }}"></a></li>
            </ul>
          </div>
          <p class="lorem_ipsum_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate</p>
        </div>
      </div>
      <!-- footer section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
        <div class="container">
          <p class="copyright_text">Copyright 2019 All Right Reserved - More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
        </div>
      </div>
      <!-- copyright section end -->

    {% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-3.0.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugin.js') }}"></script>
    <!-- sidebar -->
    <script src="{{ url_for('static', filename='js/jquery.mCustomScrollbar.concat.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
    <!-- javascript --> 
    <script src="{{ url_for('static', filename='js/owl.carousel.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script>
      $('#myCarousel').carousel({
             interval: false
         });
 
         //scroll slides on swipe for touch enabled devices
 
         $("#myCarousel").on("touchstart", function(event){
 
             var yClick = event.originalEvent.touches[0].pageY;
             $(this).one("touchmove", function(event){
 
                 var yMove = event.originalEvent.touches[0].pageY;
                 if( Math.floor(yClick - yMove) > 1 ){
                     $(".carousel").carousel('next');
                 }
                 else if( Math.floor(yClick - yMove) < -1 ){
                     $(".carousel").carousel('prev');
                 }
             });
             $(".carousel").on("touchend", function(){
                 $(this).off("touchmove");
             });
         });
    </script>

    {%- endblock scripts %}
{%- endblock body %}

app/templates/contact.html
{% extends "base.html" %}

{% block content %}
<!-- contact section start -->
{% include 'sections/contact_section.html' %}
<!-- contact section end -->
<!-- join us section start -->
{% include 'sections/joinus_section.html' %}
<!-- join us section end -->
{% endblock content %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
  {% include 'sections/banner_section.html' %}
  <!-- banner section end -->
  <!-- about section start -->
  {% include 'sections/about_section.html' %}
  <!-- about section end -->
  <!-- service section start -->
  {% include 'sections/service_section.html' %}
  <!-- service section end -->
  <!--discount section start -->
  {% include 'sections/discount_section.html' %}
  <!-- discount section end -->
  <!-- client section start --> 
  {% include 'sections/client_section.html' %}
  <!-- client section end -->
  <!-- contact section start -->
  {% include 'sections/contact_section.html' %}
  <!-- contact section end -->
  <!-- join us section start -->
  {% include 'sections/joinus_section.html' %}
  <!-- join us section end -->
{% endblock content %}

<!-- {% block footer %}
{% endblock footer %}

{% block copyright %}
{% endblock copyright %} -->

app/templates/pricing.html
{% extends "base.html" %}

{% block content %}
<!--discount section start -->
{% include 'sections/discount_section.html' %}
<!-- discount section end -->
<!-- client section start --> 
{% include 'sections/client_section.html' %}
<!-- client section end -->
<!-- join us section start -->
{% include 'sections/joinus_section.html' %}
<!-- join us section end -->
{% endblock content %}

app/templates/sections/about_section.html
<div class="about_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p class="unique_text">The unique story</p>
          <h1 class="years_text">52 Years of Experience</h1>
          <p class="ipsum_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velitLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit</p>
          <div class="read_more_bt"><a href="#">READ MORE</a></div>
        </div>
        <div class="col-md-6">
          <div class="image_2"><img src="{{ url_for('static', filename='images/img-2.png') }}"></div>
        </div>
      </div>
    </div>
  </div>

app/templates/sections/banner_section.html
<div class="banner_section">
    <section class="slide-wrapper">
      <div class="container">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                  <li data-target="#myCarousel" data-slide-to="1"></li>
                  <li data-target="#myCarousel" data-slide-to="2"></li>
                  <li data-target="#myCarousel" data-slide-to="3"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                  <div class="carousel-item active">
                      <div class="container">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="image_1"><img src="{{ url_for('static', filename='images/img-1.png') }}"></div>
                          </div>
                          <div class="col-md-6">
                            <h1 class="achive_text">Achive Your Style</h1>
                            <p class="best_text">The best place for your hairstyle</p>
                            <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
                            <div class="appointment_bt"><a href="#">Make an appointment</a></div>
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="container">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="image_1"><img src="{{ url_for('static', filename='images/img-1.png') }}"></div>
                          </div>
                          <div class="col-md-6">
                            <h1 class="achive_text">Achive Your Style</h1>
                            <p class="best_text">The best place for your hairstyle</p>
                            <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
                            <div class="appointment_bt"><a href="#">Make an appointment</a></div>
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="container">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="image_1"><img src="{{ url_for('static', filename='images/img-1.png') }}"></div>
                          </div>
                          <div class="col-md-6">
                            <h1 class="achive_text">Achive Your Style</h1>
                            <p class="best_text">The best place for your hairstyle</p>
                            <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
                            <div class="appointment_bt"><a href="#">Make an appointment</a></div>
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="container">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="image_1"><img src="{{ url_for('static', filename='images/img-1.png') }}"></div>
                          </div>
                          <div class="col-md-6">
                            <h1 class="achive_text">Achive Your Style</h1>
                            <p class="best_text">The best place for your hairstyle</p>
                            <p class="lorem_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
                            <div class="appointment_bt"><a href="#">Make an appointment</a></div>
                          </div>
                        </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
    </section>
  </div>

app/templates/sections/client_section.html
<div class="client_section layout_padding">
    <h1 class="client_taital">What is Say Our Customer</h1>
    <div class="container">
      <div id="main_slider" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="row">
              <div class="col-md-6">
                <div class="alex_bg">
                  <h3 class="alex_text">Alex jorze</h3>
                  <p class="reader_text">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="alex_bg">
                  <h3 class="alex_text">Stip mark</h3>
                  <p class="reader_text">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="row">
              <div class="col-md-6">
                <div class="alex_bg">
                  <h3 class="alex_text">Alex jorze</h3>
                  <p class="reader_text">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="alex_bg">
                  <h3 class="alex_text">Stip mark</h3>
                  <p class="reader_text">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="row">
              <div class="col-md-6">
                <div class="alex_bg">
                  <h3 class="alex_text">Alex jorze</h3>
                  <p class="reader_text">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="alex_bg">
                  <h3 class="alex_text">Stip mark</h3>
                  <p class="reader_text">t is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
          <i class="fa fa-long-arrow-left"></i>
        </a>
        <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
          <i class="fa fa-long-arrow-right"></i>
        </a>
      </div>
    </div>
  </div>

app/templates/sections/contact_section.html
<div class="contact_section layout_padding">
    <div class="container">
      <h1 class="contact_taital">Contact Us</h1>
      <div class="contact_section_2">
        <div class="row">
          <div class="col-md-6">
            <div class="mail_section">
              <form method="POST">
                    {{ form.hidden_tag() }}
                    <!-- <input type="text" class="mail_text" placeholder="{{ form.username.label }}" name="text"> -->
                    {{ form.username(class_="mail_text", placeholder="Username") }}
                    <!-- <input type="text" class="mail_text" placeholder="Email" name="text"> -->
                    {{ form.email(class_="mail_text", placeholder="Email") }}
                    <!-- <input type="text" class="mail_text" placeholder="Phone Number" name="text"> -->
                    {{ form.phonenumber(class_="mail_text", placeholder="Phone") }}
                    <!-- <textarea class="massage-bt" placeholder="Massage" rows="5" id="comment" name="Massage"></textarea> -->
                    {{ form.message(class_="massage-bt", placeholder="Massage", row="5") }}
                    <!-- <div class="send_bt"><a href="#">SEND</a></div> -->
                    <div class="send_bt">{{ form.submit()}}</div>
                    <!-- <div class="send_bt">{{ form.submit() }}</div> -->
              </form>
            </div>
          </div>
          <div class="col-md-6">
            <div class="map_text"><img src="{{ url_for('static', filename='images/call-icon-1.png') }}"><span class="call_text_left">+01 9876543210</span>
            <div class="map_text"><img src="{{ url_for('static', filename='images/call-icon-1.png') }}"><span class="call_text_left">+01 9876543210</span>
            <div class="map_text"><img src="{{ url_for('static', filename='images/mail-icon-1.png') }}"><span class="call_text_left">democheck@gmail.com</span>
            <div class="map_text_1"><img src="{{ url_for('static', filename='images/map-icon-1.png') }}"><span class="call_text_left">t is a long established...</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>

app/templates/sections/discount_section.html
<div class="discount_section layout_padding">
    <div class="container">
      <div class="discount_bg">
        <div class="row">
          <div class="col-sm-8">
            <h1 class="get_tetx">GET FLAT 25% DISCOUNT</h1>
            <h1 class="every_tetx">ON EVERY SUNDAY OF DECEMBER</h1>
            <h1 class="promo_tetx">USE PROMO CODE: BARBERDIS</h1>
          </div>
          <div class="col-sm-4">
            <div class="image_6"><img src="{{ url_for('static', filename='images/img-6.png') }}"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/templates/sections/joinus_section.html
<div class="join_section">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="member_text">Want To Be A Member? Join With Us</h1>
        </div>
        <div class="col-md-6">
          <div class="join_bt"><a href="#">SEND</a></div>
        </div>
      </div>
    </div>
  </div>

app/templates/sections/service_section.html
<div class="service_section layout_padding">
    <div class="container">
      <h1 class="services_text">Our Services</h1>
      <p class="dolor_text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore </p>
      <div class="service_section_2">
        <div class="row">
          <div class="col-sm-4">
            <div class="image_3"><img src="{{ url_for('static', filename='images/img-3.png') }}"></div>
            <h1 class="classic_text">CLASSIC HAIR CUT</h1>
            <p class="consectetur_text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
            <div class="read_bt_main">
              <div class="read_bt"><a href="#">Read More</a></div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="image_3"><img src="{{ url_for('static', filename='images/img-4.png') }}"></div>
            <h1 class="classic_text">CLASSIC HAIR CUT</h1>
            <p class="consectetur_text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
            <div class="read_bt_main">
              <div class="read_bt"><a href="#">Read More</a></div>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="image_3"><img src="{{ url_for('static', filename='images/img-5.png') }}"></div>
            <h1 class="classic_text">CLASSIC HAIR CUT</h1>
            <p class="consectetur_text">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
            <div class="read_bt_main">
              <div class="read_bt"><a href="#">Read More</a></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/templates/services.html
{% extends "base.html" %}

{% block content %}
 <!-- service section start -->
 {% include 'sections/service_section.html' %}
  <!-- service section end -->
  <!-- join us section start -->
  {% include 'sections/joinus_section.html' %}
  <!-- join us section end -->
{% endblock content %}